ci:
  autofix_prs: false
  autoupdate_branch: devel
  autoupdate_schedule: quarterly
  submodules: true
repos:
- repo: https://github.com/BlankSpruce/gersemi
  rev: 0.22.3
  hooks:
  - id: gersemi
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.13.3
  hooks:
  - id: ruff
    args:
    - --fix
    - --exit-non-zero-on-fix
  - id: ruff-format
- repo: https://github.com/pre-commit/mirrors-clang-format
  rev: v21.1.2
  hooks:
  - id: clang-format
    args:
    - '--style={BasedOnStyle: Mozilla, SortIncludes: false}'
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: trailing-whitespace
